version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: snippetboxDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: snippetboxDB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"