# .github/workflows/go.yml

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Run Go Tests with Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Install MySQL client (optional)
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Run Tests (all)
        run: go test -v ./...
